config/routes.rb
Rails.application.routes.draw do
  resources :agencia
  resources :agencia

end

app/models/agencium.rb
class Agencium < ActiveRecord::Base
end

app/controllers/agencia_controller.rb
class AgenciaController < ApplicationController
  before_action :set_agencium, only: [:show, :edit, :update, :destroy]

  # GET /agencia
  # GET /agencia.json
  def index
    @agencia = Agencium.all
  end

  # GET /agencia/1
  # GET /agencia/1.json
  def show
  end

  # GET /agencia/new
  def new
    @agencium = Agencium.new
  end

  # GET /agencia/1/edit
  def edit
  end

  # POST /agencia
  # POST /agencia.json
  def create
    @agencium = Agencium.new(agencium_params)

    respond_to do |format|
      if @agencium.save
        format.html { redirect_to @agencium, notice: 'Agencium was successfully created.' }
        format.json { render :show, status: :created, location: @agencium }
      else
        format.html { render :new }
        format.json { render json: @agencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agencia/1
  # PATCH/PUT /agencia/1.json
  def update
    respond_to do |format|
      if @agencium.update(agencium_params)
        format.html { redirect_to @agencium, notice: 'Agencium was successfully updated.' }
        format.json { render :show, status: :ok, location: @agencium }
      else
        format.html { render :edit }
        format.json { render json: @agencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencia/1
  # DELETE /agencia/1.json
  def destroy
    @agencium.destroy
    respond_to do |format|
      format.html { redirect_to agencia_url, notice: 'Agencium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agencium
      @agencium = Agencium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agencium_params
      params.require(:agencium).permit(:usuario, :mensaje, :fecha)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/agencia_helper.rb
module AgenciaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agencia/_form.html.erb
<%= form_for(@agencium) do |f| %>
  <% if @agencium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agencium.errors.count, "error") %> prohibited this agencium from being saved:</h2>

      <ul>
      <% @agencium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuario %><br>
    <%= f.text_field :usuario %>
  </div>
  <div class="field">
    <%= f.label :mensaje %><br>
    <%= f.text_area :mensaje %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agencia/edit.html.erb
<h1>Editing Agencium</h1>

<%= render 'form' %>

<%= link_to 'Show', @agencium %> |
<%= link_to 'Back', agencia_path %>

app/views/agencia/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Agencia</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Mensaje</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agencia.each do |agencium| %>
      <tr>
        <td><%= agencium.usuario %></td>
        <td><%= agencium.mensaje %></td>
        <td><%= agencium.fecha %></td>
        <td><%= link_to 'Show', agencium %></td>
        <td><%= link_to 'Edit', edit_agencium_path(agencium) %></td>
        <td><%= link_to 'Destroy', agencium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agencium', new_agencium_path %>

app/views/agencia/new.html.erb
<h1>New Agencium</h1>

<%= render 'form' %>

<%= link_to 'Back', agencia_path %>

app/views/agencia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @agencium.usuario %>
</p>

<p>
  <strong>Mensaje:</strong>
  <%= @agencium.mensaje %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @agencium.fecha %>
</p>

<%= link_to 'Edit', edit_agencium_path(@agencium) %> |
<%= link_to 'Back', agencia_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>